version: 1.0.{build}
image: Visual Studio 2019
environment:
  nodejs_version: "18"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "<your-email>"
  - git config --global user.name "<your-name>"
  - npm run deploy